export const ColumnsBitacoraOpts = {
    account: [
        { id: "jjf", value: "JJF" },
        { id: "zapopan", value: "Zapopan" },
    ],

    area_responsable: [
        { id: "infraestructura_comercio", value: "Infraestructura de comercio", label: "infraestructura_comercio" },
        { id: "servicios_municipales", value: "Servicios municipales", label: "servicios_municipales" },
        { id: "gestion_integral", value: "Gestión integral", label: "gestion_integral" },
        { id: "secretaria_ayuntamiento", value: "Secretaría del ayuntamiento", label: "secretaria_ayuntamiento" },
        { id: "desarrollo_economico", value: "Desarrollo económico", label: "desarrollo_economico" },
        { id: "construccion_comunidad", value: "Construcción comunidad", label: "construccion_comunidad" },
        { id: "dif", value: "DIF", label: "dif" },
        { id: "tesoreria", value: "Tesorería", label: "tesoreria" },
        { id: "cfe", value: "CFE", label: "cfe" },
        { id: "siapa", value: "SIAPA", label: "siapa" },
        { id: "siop", value: "SIOP", label: "siop" },
        { id: "otras_coordinaciones", value: "Otras coordinaciones", label: "otras_coordinaciones" },
        { id: "otras_dependencias_estatales", value: "Otras dependencias estatales", label: "otras_dependencias_estatales" },
        { id: "presidencia", value: "Presidencia", label: "presidencia" },
        { id: "guadalajara", value: "Guadalajara", label: "guadalajara" },
        { id: "inspeccion_vigilancia", value: "Inspección y vigilancia", label: "inspeccion_vigilancia" },
        { id: "pcyb", value: "PCyB", label: "pcyb" },
        { id: "cercania_ciudadana", value: "Cercanía ciudadana", label: "cercania_ciudadana" },
        { id: "salud_zapopan", value: "Salud Zapopan", label: "salud_zapopan" },
        { id: "comisaria", value: "Comisaría", label: "comisaria" },
        { id: "comude", value: "COMUDE", label: "comude" },
        { id: "caec", value: "CAEC (Boletos Charros)", label: "caec" },
        { id: "sindicatura", value: "Sindicatura", label: "sindicatura" },
        { id: "administracion_inovacion_gubernamental", value: "Administración e Innovación Gubernamental", label: "administracion_inovacion_gubernamental" },
        { id: "amim", value: "AMIM", label: "amim" },
        { id: "cursos_parque_ninas_ninos", value: "Cursos en el Parque de las niñas y  niños", label: "cursos_parque_ninas_ninos" },
        { id: "romeria", value: "Romería", label: "romeria" },
        { id: "contraloria_ciudadana", value: "Contraloría ciudadana", label: "contraloria_ciudadana" },
        { id: "toc_toc", value: "Toc toc", label: "toc_toc" },
        { id: "otros", value: "Otros", label: "otros" },
        { id: "equipo_campana", value: "Equipo campaña", label: "equipo_campana" },
        { id: "fiesta_de_abril", value: "Fiesta de Abril", label: "fiesta_de_abril" },
        { id: "desabasto_de_agua_en_lomas_de_centinela", value: "Desabasto de agua en Lomas de Centinela", label: "desabasto_de_agua_en_lomas_de_centinela" },
        { id: "infraestrucura_en_comercio", value: "Infraestructura de Comercio", label: "infraestrucura_en_comercio" },
    ],

    category: [
        { id: "solicitud_informacion", value: "Solicitud de información", label: "solicitud_informacion" },
        { id: "canalizacion_dependencia", value: "Canalización a dependencia", label: "canalizacion_dependencia" },
        { id: "solicitudes_nuevas", value: "Solicitudes nuevas", label: "solicitudes_nuevas" },
        { id: "reportes_servicios", value: "Reportes de servicios", label: "reportes_servicios" },
        { id: "reporte_obras", value: "Reportes de obra", label: "reporte_obras" },
        { id: "reporte_externos", value: "Reportes externos", label: "reporte_externos" },
        { id: "solicitudes_especiales", value: "Solicitudes especiales", label: "solicitudes_especiales" },
        { id: "reporte_inspeccion_vigilancia", value: "Reporte de inspección y vigilancia", label: "reporte_inspeccion_vigilancia" },
        { id: "reportes_denuncias", value: "Reportes y denuncias", label: "reportes_denuncias" },
        { id: "solicitud_empleo", value: "Solicitud de empleo", label: "solicitud_empleo" },
        { id: "coyuntura", value: "Coyuntura", label: "coyuntura" },
        { id: "participacion_curso", value: "Participación en curso", label: "participacion_curso" },
        { id: "solicitud_obra", value: "Solicitud de obra", label: "solicitud_obra" },
        { id: "otros", value: "Otros", label: "otros" },
    ],

    channel: [
        { id: "comentario", value: "Comentario" },
        { id: "inbox", value: "Inbox" },
    ],

    priority: [
        { id: "baja", value: "Baja" },
        { id: "media", value: "Media" },
        { id: "alta", value: "Alta" },
    ],

    status: [
        { id: "pendiente", value: "Pendiente" },
        { id: "en_proceso", value: "En Proceso" },
        { id: "resuelto", value: "Resuelto" },
    ],
    social_network: [
        { id: "x", value: "X" },
        { id: "tiktok", value: "Tiktok" },
        { id: "instagram", value: "Instagram" },
        { id: "facebook", value: "Facebook" },
    ]
};
