export const ColumnsBitacoraOpts = {
    account: [
        { id: "jjf", value: "JJF" },
        { id: "zapopan", value: "Zapopan" },
    ],

    area_responsable: [
        { id: "infraestructura_de_comercio", value: "Infraestructura de comercio", label: "infraestructura_de_comercio" },
        { id: "servicios_municipales", value: "Servicios municipales", label: "servicios_municipales" },
        { id: "gestión_integral", value: "Gestión integral", label: "gestión_integral" },
        { id: "secretaría_del_ayuntamiento", value: "Secretaría del ayuntamiento", label: "secretaría_del_ayuntamiento" },
        { id: "desarrollo_económico", value: "Desarrollo económico", label: "desarrollo_económico" },
        { id: "construcción_comunidad", value: "Construcción comunidad", label: "construcción_comunidad" },
        { id: "dif", value: "DIF", label: "dif" },
        { id: "tesorería", value: "Tesorería", label: "tesorería" },
        { id: "cfe", value: "CFE", label: "cfe" },
        { id: "siapa", value: "SIAPA", label: "siapa" },
        { id: "siop", value: "SIOP", label: "siop" },
        { id: "otras_coordinaciones", value: "Otras coordinaciones", label: "otras_coordinaciones" },
        { id: "otras_dependencias_estatales", value: "Otras dependencias estatales", label: "otras_dependencias_estatales" },
        { id: "presidencia", value: "Presidencia", label: "presidencia" },
        { id: "guadalajara", value: "Guadalajara", label: "guadalajara" },
        { id: "inspección_y_vigilancia", value: "Inspección y vigilancia", label: "inspección_y_vigilancia" },
        { id: "pcyb", value: "PCyB", label: "pcyb" },
        { id: "cercanía_ciudadana", value: "Cercanía ciudadana", label: "cercanía_ciudadana" },
        { id: "salud_zapopan", value: "Salud Zapopan", label: "salud_zapopan" },
        { id: "comisaría", value: "Comisaría", label: "comisaría" },
        { id: "comude", value: "COMUDE", label: "comude" },
        { id: "caec_(boletos_charros)", value: "CAEC (Boletos Charros)", label: "caec_(boletos_charros)" },
        { id: "sindicatura", value: "Sindicatura", label: "sindicatura" },
        { id: "administración_e_inovación_gubernamental", value: "Administración e Innovación Gubernamental", label: "administración_inovación_gubernamental" },
        { id: "amim", value: "AMIM", label: "amim" },
        { id: "cursos_en_el_parque_de_las_niñas_y_niños", value: "Cursos en el Parque de las niñas y niños", label: "cursos_en_el_parque_de_las_niñas_y_niños" },
        { id: "romeria", value: "Romería", label: "romeria" },
        { id: "contraloría_ciudadana", value: "Contraloría ciudadana", label: "contraloría_ciudadana" },
        { id: "toc_toc", value: "Toc toc", label: "toc_toc" },
        { id: "otros", value: "Otros", label: "otros" },
        { id: "equipo_campaña", value: "Equipo campaña", label: "equipo_campaña" },
        { id: "fiesta_de_abril", value: "Fiesta de Abril", label: "fiesta_de_abril" },
        { id: "desabasto_de_agua_en_lomas_de_centinela", value: "Desabasto de agua en Lomas de Centinela", label: "desabasto_de_agua_en_lomas_de_centinela" },
    ],

    category: [
        { id: "solicitud_de_información", value: "Solicitud de información", label: "solicitud_de_información" },
        { id: "canalizacion_a_dependencia", value: "Canalización a dependencia", label: "canalizacion_a_dependencia" },
        { id: "solicitudes_nuevas", value: "Solicitudes nuevas", label: "solicitudes_nuevas" },
        { id: "reportes_de_servicios", value: "Reportes de servicios", label: "reportes_de_servicios" },
        { id: "reportes_de_obras", value: "Reportes de obra", label: "reportes_obras" },
        { id: "reportes_externos", value: "Reportes externos", label: "reportes_externos" },
        { id: "solicitudes_especiales", value: "Solicitudes especiales", label: "solicitudes_especiales" },
        { id: "reporte_inspeccion_vigilancia", value: "Reporte de inspección y vigilancia", label: "reporte_inspeccion_vigilancia" },
        { id: "reportes_denuncias", value: "Reportes y denuncias", label: "reportes_denuncias" },
        { id: "solicitud_empleo", value: "Solicitud de empleo", label: "solicitud_empleo" },
        { id: "coyuntura", value: "Coyuntura", label: "coyuntura" },
        { id: "participacion_curso", value: "Participación en curso", label: "participacion_curso" },
        { id: "solicitud_obra", value: "Solicitud de obra", label: "solicitud_obra" },
        { id: "otros", value: "Otros", label: "otros" },
    ],

    channel: [
        { id: "comentarios", value: "Comentarios" },
        { id: "inbox", value: "Inbox" },
    ],

    priority: [
        { id: "baja", value: "Baja" },
        { id: "media", value: "Media" },
        { id: "alta", value: "Alta" },
    ],

    status: [
        { id: "pendiente", value: "Pendiente" },
        { id: "en_proceso", value: "En Proceso" },
        { id: "resuelto", value: "Resuelto" },
        { id: "dirección", value: "Dirección" },
    ],
    social_network: [
        { id: "x", value: "X" },
        { id: "tiktok", value: "Tiktok" },
        { id: "instagram", value: "Instagram" },
        { id: "facebook", value: "Facebook" },
    ],
    excluded_view: [
        { id: "siop", value: "SIOP", label: "siop" },
        { id: "otras_coordinaciones", value: "Otras coordinaciones", label: "otras_coordinaciones" },
        { id: "caec", value: "CAEC (Boletos Charros)", label: "caec" },
        { id: "romeria", value: "Romería", label: "romeria" },
        { id: "toc_toc", value: "Toc toc", label: "toc_toc" },
        { id: "otros", value: "Otros", label: "otros" },
        { id: "equipo_campana", value: "Equipo campaña", label: "equipo_campana" },
        { id: "fiesta_de_abril", value: "Fiesta de Abril", label: "fiesta_de_abril" },
        { id: "desabasto_de_agua_en_lomas_de_centinela", value: "Desabasto de agua en Lomas de Centinela", label: "desabasto_de_agua_en_lomas_de_centinela" },
    ]
};
